app_config_file_path: /project/DPDS/Xiao_lab/s221963/2025_LLMsAgents/example_project_small/medgemma27b_P07/config_llm_app.yaml
dataset_id: lung
framework: huggingface
home_path: /project/DPDS/Xiao_lab/s221963/2025_LLMsAgents/example_project_small/medgemma27b_P07
input_data_id_column_name: pid
input_data_path: /project/DPDS/Xiao_lab/s221963/2025_LLMsAgents/example_project_small/data/tcga_pan_lung_samples.csv
input_text_column_name: text
json_key_list:
- tumor_size_max_dimension_stated
- tumor_size_max_dimension
- tumor_size_max_dimension_CD
- tumor_size_max_dimension_evidence
- pT_stated
- pT
- pT_CD
- pT_evidence
- pN_stated
- pN
- pN_CD
- pN_evidence
- tumor_stage_stated
- tumor_stage
- tumor_stage_CD
- tumor_stage_evidence
- histologic_diagnosis_stated
- histologic_diagnosis
- histologic_diagnosis_CD
- histologic_diagnosis_evidence
json_output_template_path: /project/DPDS/Xiao_lab/s221963/2025_LLMsAgents/example_project_small/json_output_template.json
model: google/medgemma-27b-text-it
model_id: medgemma27b
predictor: medgemma27b_P07
prompt_file_path: /project/DPDS/Xiao_lab/s221963/2025_LLMsAgents/example_project_small/prompt_p07.txt
prompt_id: P07
system_message_file_path: /project/DPDS/Xiao_lab/s221963/2025_LLMsAgents/example_project_small/system_message.txt
var_val_dict_path: /project/DPDS/Xiao_lab/s221963/2025_LLMsAgents/example_project_small/variable-value_dict.json
